const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348024322741",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR01TRE5oUlRuMkxEa21jWW95RFE2N1dhd1Z2eWVPNkQwYjBLbjZKbFRYdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWGN6N211TkJoSnRXQXdFRUQ5K2ZVbGpXUHpPR1RCVVRIUlpZTTdiYTZqOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBQjduK0t1N2NGQzN2VWlOK1FhOEo4Z0xvaGUrZldlVlRzbjVXRnZFeDMwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzQkJxSU9DODR0V0FHeVFpZG5zWkd3WjhXK1pIVWJsUGh1alg2QmtKaG5nPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitKNDZGUjVHNGkyR0U1Vi9YNzFHYWVQTGRoRzNqQ096VXNqcysxekxZMHM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlZqKyttVjF6RmFac2M0ZUM4YzVLWHl2WW9iUGNNMUhyZ0FPTWh5RHRtUjg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid05Jb2E0eFhXZFBmT3Z0RTB2dEhLRGhCV3MwZTVwSXl6Wk14ZGhjb3NsMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM3B5by9rNGR6Tm8yZ2FCK0tBT0VBcGhTaTZHSDFQZCtjWGt0Q0VHd1VYWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZFQjhPK3kyNDNPQmhJK1NscjUyakM3NTg1MlJKN25UWXVIdmNqSlU4bHZQV2J1OEQyZ1NOSHgwWUg1TUVqT0FZcTYrb0k2b0ViL0V2WGluMzBwd2dBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjE3LCJhZHZTZWNyZXRLZXkiOiJVam15OTdzMnVFYW5TVHlmbkkxaGdzOGVSaVhseEM1M0RCUEM2QkVXcWNJPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJVeWhnNXFqNlRYV2VLWHZJRU5mY2hnIiwicGhvbmVJZCI6ImUyODM2MGI4LWI5ZWEtNGMwYy05MmZjLWYzYjZlZTU0ZmIxNCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIzODFRKzM1cE5pVzhIcnBtSW11ak5wWGUwUm89In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTjJKS05UdUQ1K2NaaHo3UXNPVVdxOWxHNE53PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjgzMkZCR0RaIiwibWUiOnsiaWQiOiIyMzQ4MDI0MzIyNzQxOjY5QHMud2hhdHNhcHAubmV0IiwibmFtZSI6ImxlZ2FjeSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSjc2eU5zQkVNVG95NzBHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiRGJKVE9RVXY2ZENHSTB0c1BtbnRTbDBmaWsrWEppUndzeHZlSitWU2prZz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiQ1d1dG12dWN3Qys3eXk0emVPRjZmbWhtVVhSN0lMcVZxMTI2UHNVWmFGZnYweEdjeG9qdEVNNWF6NnVRY1l2OVIvRVBUek9nVEpGa2c4R0xoL2s1Q1E9PSIsImRldmljZVNpZ25hdHVyZSI6IjYyOFNZNG9DajFkMTJuN1VZcDNETzJFWmpjekJHMElxNThvQlhxYlJxaUZXbE5uc2JMelZtajFPT0FUb0o2enp3alhkRlFjb3NLcUZoVzdidE5BQ2lnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODAyNDMyMjc0MTo2OUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJRMnlVemtGTCtuUWhpTkxiRDVwN1VwZEg0cFBseVlrY0xNYjNpZmxVbzVJIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM5NzgxMjAxfQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
