const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2347074111970",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUNvVGI2T25IVHh4QktORmpyWXp0cEQvdWZQVGs1UCswRDk2Z0wvQmpuZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRnBndjJBVmxHcHpaYUJMaWRmUStiTjFTN1lnT3habUQyT2Q3NUhNWmZUYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4Tjd1TG1GYTFYWEc1bmRqUXhTMDdLUVdncWxNOUoyenYzeitHY1gyaTA0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTMFZacGJIU0xkUFMzYjFtcW9xQlo1WVpQd0t1aGFTK3BrMGdkUGNqUWwwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdESTZXeW96OTgxSFF1cGJyMzhUaUh5a1BPczBvQkpoK1BVT3gweHc2RTA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilh5V1pqN1NNNmhUMUZndWZYZVJ1dUw3TE1FQTRLRy96Zk5ZYzJsMDZYVTQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQURUU2xub3RCRURPYjAzTGdocmkwLzNjcVBmQnU5VWFZQlVQTFJJSnJXYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRlZqNDIxbWg1Vm93L3RzaFZFbjU0UDBzNStEWjFYYm5CNW8zVGlGUy9Baz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZZd0RHWVE2YVUrNi9LdXhpNDJkNUVUT0cvdDA5c0JWc1RWbFBpQWU3UC9MK0xZck9DbThrdnJTWUhuU3U4WFNYRHJ1R3YyWnJnbXBPRWI3eUExN0RBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTkxLCJhZHZTZWNyZXRLZXkiOiJaUU1hcURoaHJXT3BYRnlUd0xaNzFaN1BkS1JXT2VTVUpRU2lwZjBhbWNjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI3R256eXQxWlJwLTJiNFN4Tm9WTnFRIiwicGhvbmVJZCI6IjkzOTM4NDE1LTQxOTgtNDYzYS1iMGY4LTc2MGE0Mzg5NzI2OCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJSWTc1aHJsdnQxSGdGOEljN0wyazZjdEo3VlU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaElKb1hNZ3VNSUFzQkZkRE5qVEFiYjNZOTlRPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Ik0yWEczS0RNIiwibWUiOnsiaWQiOiIyMzQ3MDc0MTExOTcwOjE1QHMud2hhdHNhcHAubmV0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKR3ZxcjBERUpiNXk3MEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI3U3MvOFMwRUZwOEVOQlVHaUYwZE0zTmVycW1wbkNxODN4cUlKNHkyeHk4PSIsImFjY291bnRTaWduYXR1cmUiOiJlSXNYVDgzSkkrVUo4WS9Dc2xoTVNVNjJ0STYyRGtKdDdrUEhxQXdiaCtGMVYzeVRlaTNhejF2SHJOd25iTHM2NENmdk9pd1JVT3o4T3lxdmowOGpDdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiVlB5bm9INWxqQzgwbGxMdzR5c3p0ditVQXhGTXJxZ2puTExSUEpqK1Z3QkI3OWVISzFJQ3pJQ203TW9NeXlPcDFmSmxBZkN1TExrQjMyYmdZTmF1Q3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ3MDc0MTExOTcwOjE1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmUwclAvRXRCQmFmQkRRVkJvaGRIVE56WHE2cHFad3F2TjhhaUNlTXRzY3YifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3Mzk3ODMzMzAsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBS01UIn0=",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
